package com.sap.repo.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.List;

@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(description = "Details about the ErrorDetails")
public class ErrorDetails {
    @Id
    @Column
    @ApiModelProperty(notes = "Unique Id for Error (generated by UUID)")
    private String id;

    @Column
    @ApiModelProperty(notes = "Solution for Error")
    private String solution;

    @ElementCollection
    @ApiModelProperty(notes = "List of keywords for Error of type String")
    private List<String> keywords;

    @Column
    @ApiModelProperty(notes = "AuthorId for Error")
    private String authorId;

    @Column
    @ApiModelProperty(notes = "Description for Error")
    private String description;

    @Column
    @ApiModelProperty(notes = "Solution type For Error")
    private String type;

}